services:

  db:
    image: mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secrET123#@
     
    volumes:
      - './dbvol/:/var/lib/mysql'
      - ./dbscript:/docker-entrypoint-initdb.d/:ro
    networks:
      - makecrew_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secrET123#@
    depends_on:
      - db
    networks:
      - makecrew_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DOCKER_ENV: 'true' 
    networks:
      - makecrew_net

  nginx:
    image: nginx:latest
    ports:
      - "8009:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - makecrew_net


  

networks:
  makecrew_net:
    driver: bridge
